# This Anchor.toml file is used to setup programs and accounts for UI development
# Instead of running the normal test suite, we are running app/setup.ts
# Instead of reinventing the wheel, we are using anchor test to facilitate deployment
[features]
seeds = true

[programs.localnet]
staking = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/default_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 app/setup.ts"
