[package]
name = "staking"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "staking"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
mock-clock = []
wasm = ["no-entrypoint"]
default = []

[dependencies]
borsh = {version = "0.9.3", features = ["const-generics"]}
anchor-lang = "0.22.0"
anchor-spl = "0.22.0"
wasm-bindgen = "0.2.79"
js-sys = "0.3.56"
