[package]
name = "staking"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "staking"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.22.0"
anchor-spl = {version = "0.22.0", features = ["governance"]}
solana-program = "1.9.7"
spl-governance-addin-api = { git = "https://github.com/solana-labs/solana-program-library", tag="governance-v2.2.3"}
