# This workflow will run `anchor test`
name: Anchor Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
  steps:
  - uses: actions/checkout@v2
  - name: Setup Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '16.13'
  - name: Install yarn
    run: npm install yarn
  - name: Yarn install everything else
    run: yarn install
  - name: Anchor test
    run: anchor test
    
