# This workflow will run `anchor test`
name: Anchor Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13'
    - name: Install yarn
      run: corepack enable
    - name: Yarn install everything else
      run: yarn install
    - name: Did Yarn install do anything?
      run: yarn list
    - name: Anchor test
      run: anchor test

