[features]
seeds = true

[programs.localnet]
staking = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
governance = "pythGovernance11111111111111111111111111111"

[programs.devnet]
governance = "GTesTBiEWE32WHXXE2S4XbZvA5CrEc4xs6ZgRe895dP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/keypairs/default_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/staking.ts"

[validator]
ledger_dir = "./.anchor/test-ledger"

[path]
idl_path = "./target/idl/staking.json"
binary_path = "./target/deploy/staking.so"
governance_path = "./target/deploy/governance.so"
