anchor_version = "0.24.1"

[features]
seeds = true

[workspace]
members = ["programs/staking"]

[programs.localnet]
pyth_staking_program = "sta99txADjRfwHQQMNckb8vUN4jcAAhN2HBMTR2Ah6d"
governance = "GovFUVGZWWwyoLq8rhnoVWknRFkhDSbQiSoREJ5LiZCV"
chat = "gCHAtYKrUUktTVzE4hEnZdLV4LXrdBf6Hh9qMaJALET"

[programs.devnet]
pyth_staking_program = "sta99txADjRfwHQQMNckb8vUN4jcAAhN2HBMTR2Ah6d"
governance = "GovFUVGZWWwyoLq8rhnoVWknRFkhDSbQiSoREJ5LiZCV"

[programs.mainnet]
pyth_staking_program = "sta99txADjRfwHQQMNckb8vUN4jcAAhN2HBMTR2Ah6d"
governance = "GovFUVGZWWwyoLq8rhnoVWknRFkhDSbQiSoREJ5LiZCV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "./tests/keypairs/default_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/staking.ts"

[validator]
ledger_dir = "./.anchor/test-ledger"

[path]
idl_path = "./target/idl/staking.json"
binary_path = "./target/deploy/staking.so"
governance_path = "./target/deploy/governance.so"
chat_path = "./target/deploy/chat.so"
